apiVersion: apps/v1
kind: Deployment
metadata:
  name: studystorm
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: studystorm
  template:
    metadata:
      labels:
        app: studystorm
    spec:
      containers:
      - name: studystorm-pod
        image: studystorm-app
        ports: 
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  type: NodePort
  selector:
    app: studystorm
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 3000
