version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/auth
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy  # Wait for the db service to be healthy before starting app

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  # Health check command
      timeout: 10s
      retries: 5
      interval: 5s

  email-service:
    image: notification-service
    ports:
      - 4000:4000
