spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: "avishkatest123@gmail.com"
    password: "rvhe fqfh npka kfan"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082